#region Usings

using System.Numerics;
using Command;
using Move;

#endregion

namespace Factory
{
    public class AutoGeneratedMovableAdapter : IMovable
    {
        private readonly IMovable adapteeToMove;
        private readonly IResolvable ioC;

        public AutoGeneratedMovableAdapter(IMovable adapteeToMove, IResolvable ioC)
        {
            this.adapteeToMove = adapteeToMove;
            this.ioC = ioC;
        }

        public Vector2 Position
        {
            get => ioC.Resolve<Vector2>("Object.GetPosition", adapteeToMove);
            set => ioC.Resolve<ICommand>("Object.SetPosition", adapteeToMove, value).Execute();
        }

        public Vector2 Velocity => ioC.Resolve<Vector2>("Object.GetVelocity", adapteeToMove);
    }
}