#region Usings

using Factory;
using FluentAssertions;
using Moq;
using Move;
using NUnit.Framework;

#endregion

namespace Adapter.Tests
{
    public class WhenResolvingAdapters : TestBase
    {
        [Test]
        public void MovableAdapterGenerates()
        {
            IResolvable ioc = new IoC();
            var objectToMove = new Mock<IMovable>();

            var adapter = ioc.Resolve<IMovable>("Adapter", typeof(IMovable), objectToMove.Object);

            adapter.Should().BeOfType<AutoGeneratedMovableAdapter>();
        }
    }
}